"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, ImageOff, ShoppingCart, Star } from "lucide-react";
import { addCartItem, createCart, getProduct } from "@/lib/api";
import { money, Product, productImage, salePrice } from "@/lib/catalog";
import { getCartId, getCustomerId, isAuthenticated, setCartId } from "@/lib/session";
export default function ProdutoDetalhe() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [product, setProduct] = useState<Product | null>(null); const [error, setError] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => { getProduct(Number(id)).then(setProduct).catch((e) => setError(e.message)); }, [id]);
  const add = async () => { if (!isAuthenticated()) { router.push(`/perfil?next=${encodeURIComponent(`/produto/${id}`)}&loginRequired=1`); return; } setStatus("Adicionando..."); try { let cartId = getCartId(); if (!cartId) { const created = await createCart(getCustomerId()); cartId = created.id ?? created.cartId ?? null; if (!cartId) throw new Error("o backend não retornou o ID do carrinho"); setCartId(cartId); } await addCartItem(cartId, Number(id)); setStatus("Produto adicionado ao carrinho."); } catch (e) { setStatus(`Não foi possível adicionar: ${e instanceof Error ? e.message : "erro"}`); } };
  if (error) return <div className="app-shell p-5"><p className="status-box status-error">{error}</p></div>; if (!product) return <div className="app-shell p-5"><div className="skeleton aspect-square rounded-2xl" /><div className="skeleton mt-5 h-8 w-3/4 rounded" /></div>;
  const discount = product.precoPromocional ? Math.round((1 - product.precoPromocional / product.preco) * 100) : 0;
  return <div className="app-shell pb-28"><header className="px-4 py-4"><button onClick={() => router.back()}><ArrowLeft size={28} /></button></header><div className="px-4">{product.imagem ? <img src={product.imagem} alt={product.nome} className="aspect-square w-full rounded-2xl object-cover" /> : <div className="flex aspect-square flex-col items-center justify-center gap-3 rounded-2xl bg-slate-200 text-slate-500"><ImageOff size={36} /><span>Imagem não fornecida pelo backend</span></div>}</div><main className="px-4 pt-5"><h1 className="text-3xl font-black">{product.nome}</h1><div className="my-3 flex items-center gap-2"><Star className="text-blue-600" fill="currentColor" /><b>{product.mediaAvaliacao}</b><span className="text-slate-500">({product.totalAvaliacoes} avaliações)</span></div><div className="flex items-center gap-3"><strong className="text-3xl text-blue-600">{money(salePrice(product))}</strong>{product.precoPromocional && <del>{money(product.preco)}</del>}{discount > 0 && <span className="rounded-full bg-blue-100 px-2 py-1 text-blue-700">{discount}% OFF</span>}</div><p className="my-5 text-lg">{product.descricaoCurta}</p><section className="card space-y-2 p-5 text-slate-600"><h2 className="font-bold text-slate-900">Descrição e especificações</h2><p>{product.descricao}</p><p><b>SKU:</b> {product.sku}</p><p><b>Estoque disponível:</b> {product.quantidadeEstoque}</p><p><b>Dimensões:</b> {product.altura} × {product.largura} × {product.comprimento}</p><p><b>Peso:</b> {product.peso}</p></section>{status && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-blue-700">{status}</p>}</main><div className="fixed bottom-0 left-0 right-0 mx-auto max-w-[720px] border-t bg-white p-4"><button onClick={add} disabled={product.quantidadeEstoque <= 0} className="primary-button"><ShoppingCart />Adicionar ao Carrinho</button></div></div>;
}
