const CUSTOMER_KEY = "ecommerce.customerId";
const CART_KEY = "ecommerce.cartId";
const LAST_CART_KEY = "ecommerce.lastCartId";
const TOKEN_KEY = "ecommerce.authToken";
const USER_NAME_KEY = "ecommerce.userName";
const USER_EMAIL_KEY = "ecommerce.userEmail";
const USER_STATUS_KEY = "ecommerce.userStatus";
export const getCustomerId = () => Number(localStorage.getItem(CUSTOMER_KEY)) || 1;
export const setCustomerId = (id: number) => { localStorage.setItem(CUSTOMER_KEY, String(id)); localStorage.removeItem(CART_KEY); localStorage.removeItem(LAST_CART_KEY); };
export const getCartId = () => Number(localStorage.getItem(CART_KEY)) || null;
export const getLastCartId = () => Number(localStorage.getItem(LAST_CART_KEY)) || (getCustomerId() === 1 ? 1 : null);
export const setCartId = (id: number) => { localStorage.setItem(CART_KEY, String(id)); localStorage.setItem(LAST_CART_KEY, String(id)); };
export const clearCartId = () => localStorage.removeItem(CART_KEY);
export type AuthSession = { id: number; nome: string; email: string; status: string; token: string };
export const saveAuthSession = (session: AuthSession) => { localStorage.setItem(TOKEN_KEY, session.token); localStorage.setItem(USER_NAME_KEY, session.nome); localStorage.setItem(USER_EMAIL_KEY, session.email); localStorage.setItem(USER_STATUS_KEY, session.status); setCustomerId(session.id); };
export const getAuthToken = () => localStorage.getItem(TOKEN_KEY);
export const getAuthProfile = () => ({ id: getCustomerId(), nome: localStorage.getItem(USER_NAME_KEY) ?? "Usuário de teste", email: localStorage.getItem(USER_EMAIL_KEY) ?? "", status: localStorage.getItem(USER_STATUS_KEY) ?? "ATIVO" });
export const isAuthenticated = () => Boolean(getAuthToken());
export const clearAuthSession = () => { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem(USER_NAME_KEY); localStorage.removeItem(USER_EMAIL_KEY); localStorage.removeItem(USER_STATUS_KEY); localStorage.removeItem(CUSTOMER_KEY); localStorage.removeItem(CART_KEY); localStorage.removeItem(LAST_CART_KEY); };
